### ISSUE TITLE
Change function declaration instances to arrow functions. 

### ISSUE THREAD

**Issue by staranbeer** [staranbeer/css-generator#1]
Change the functions which use the function declaration  syntax: 

```js
function functionName(){
...
}
```
to the arrow function syntax:

```
const functionName = () => {
...
}
```

You will find most of these functions in the `features` and `lib` directory.

**Comment by ugbeadie** [comment]
Hello, I have changed all of them to arrow function and submitted a pr.

**Comment by staranbeer** [comment]
Hey! Thank you for taking out the time to contribute to this project, i am going to merge your pr to the main codebase. if you like the project, do not forget to star it and follow me on github :smile: thanks a lot!
