### ISSUE TITLE
Add .prettierrc to the project

### ISSUE THREAD

**Issue by staranbeer** [staranbeer/css-generator#3]
Add a .prettierrc to the project which is compatible with the current prettier style.

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by staranbeer** [comment]
Hey! sure.

To get a sense of what the app is about, you can open the deployed version of the app.

To set up the app locally, you should read through the Readme.md file. If you have any questions, let me know.

**Comment by Vinitvh** [comment]
Sure. Thank you.
